all:
	cd ../alchemist ; g++ -DSTUB_SDL=1 -Wall -g -o ../alchemist-tui/alchemist -I. elements.cpp ../alchemist-tui/main.cpp names.cpp axe.cpp axe_blade.cpp axe_handle.cpp el_list.cpp \
	test_axe.cpp game_time.cpp ; cd ..

clean:
	rm alchemist

