#!/bin/bash

echo -e "//autogenerated file, don't motify!\nenum item_id\n{" > items_id.h
for e in `cat items.txt`
do
     echo "IT_$e," >> items_id.h
done
echo "IT_MAX," >> items_id.h
echo "};" >> items_id.h

echo -e "//autogenerated file, don't motify!\nconst char * items_names[IT_MAX]=\n{" > items_names.h
for s in `cat items.txt`
do
     echo \"$s\", >> items_names.h
done
echo "};" >> items_names.h

echo -e "//autogenerated file, don't motify!\nenum category_id\n{" > categories_id.h
for e in `cat categories.txt`
do
     echo "CAT_$e," >> categories_id.h
done
echo "CAT_MAX" >> categories_id.h

echo "};" >> categories_id.h

echo -e "//autogenerated file, don't motify!\nconst char * categories_names[CAT_MAX]=\n{" > categories_names.h
for s in `cat categories.txt`
do
     echo \"$s\", >> categories_names.h
done
echo "};" >> categories_names.h

